// <auto-generated />
using System;
using DBH.EHR.Service.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DBH.EHR.Service.Migrations
{
    [DbContext(typeof(EhrPrimaryDbContext))]
    partial class EhrPrimaryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DBH.EHR.Service.Models.Entities.EhrAccessLog", b =>
                {
                    b.Property<Guid>("AccessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("access_id");

                    b.Property<string>("AccessAction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("access_action");

                    b.Property<DateTime>("AccessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accessed_at");

                    b.Property<Guid>("AccessedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("accessed_by");

                    b.Property<Guid?>("ConsentId")
                        .HasColumnType("uuid")
                        .HasColumnName("consent_id");

                    b.Property<Guid>("EhrId")
                        .HasColumnType("uuid")
                        .HasColumnName("ehr_id");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ip_address");

                    b.Property<string>("VerifyStatus")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("verify_status");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("AccessId");

                    b.HasIndex("AccessedBy", "AccessedAt");

                    b.HasIndex("EhrId", "AccessedAt");

                    b.ToTable("ehr_access_log");
                });

            modelBuilder.Entity("DBH.EHR.Service.Models.Entities.EhrFile", b =>
                {
                    b.Property<Guid>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("EhrId")
                        .HasColumnType("uuid")
                        .HasColumnName("ehr_id");

                    b.Property<Guid?>("EhrVersionVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_hash");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("file_url");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("MimeType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mime_type");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("report_type");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("FileId");

                    b.HasIndex("EhrVersionVersionId");

                    b.HasIndex("CreatedBy", "CreatedAt");

                    b.HasIndex("EhrId", "Version", "ReportType");

                    b.ToTable("ehr_files");
                });

            modelBuilder.Entity("DBH.EHR.Service.Models.Entities.EhrRecord", b =>
                {
                    b.Property<Guid>("EhrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ehr_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByDoctorId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_doctor");

                    b.Property<int>("CurrentVersion")
                        .HasColumnType("integer")
                        .HasColumnName("current_version");

                    b.Property<Guid?>("EncounterId")
                        .HasColumnType("uuid")
                        .HasColumnName("encounter_id");

                    b.Property<Guid?>("HospitalId")
                        .HasColumnType("uuid")
                        .HasColumnName("hospital_id");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.HasKey("EhrId");

                    b.HasIndex("EncounterId");

                    b.HasIndex("HospitalId", "CreatedAt");

                    b.HasIndex("PatientId", "CreatedAt");

                    b.ToTable("ehr_records");
                });

            modelBuilder.Entity("DBH.EHR.Service.Models.Entities.EhrSubscription", b =>
                {
                    b.Property<Guid>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_renew");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EhrId")
                        .HasColumnType("uuid")
                        .HasColumnName("ehr_id");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<DateOnly?>("NextBillingDate")
                        .HasColumnType("date")
                        .HasColumnName("next_billing_date");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<Guid?>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("SubscriptionId");

                    b.HasIndex("EhrId", "Status");

                    b.HasIndex("PatientId", "Status");

                    b.ToTable("ehr_subscriptions");
                });

            modelBuilder.Entity("DBH.EHR.Service.Models.Entities.EhrVersion", b =>
                {
                    b.Property<Guid>("VersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("version_id");

                    b.Property<string>("BlockchainTxHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("blockchain_tx_hash");

                    b.Property<string>("ChangeReason")
                        .HasColumnType("text")
                        .HasColumnName("change_reason");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EhrId")
                        .HasColumnType("uuid")
                        .HasColumnName("ehr_id");

                    b.Property<string>("FileHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_hash");

                    b.Property<Guid?>("PreviousVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("previous_version_id");

                    b.Property<string>("TxStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tx_status");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("VersionId");

                    b.HasIndex("BlockchainTxHash")
                        .IsUnique();

                    b.HasIndex("PreviousVersionId");

                    b.HasIndex("EhrId", "Version")
                        .IsUnique();

                    b.ToTable("ehr_versions");
                });

            modelBuilder.Entity("DBH.EHR.Service.Models.Entities.EhrAccessLog", b =>
                {
                    b.HasOne("DBH.EHR.Service.Models.Entities.EhrRecord", "EhrRecord")
                        .WithMany()
                        .HasForeignKey("EhrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EhrRecord");
                });

            modelBuilder.Entity("DBH.EHR.Service.Models.Entities.EhrFile", b =>
                {
                    b.HasOne("DBH.EHR.Service.Models.Entities.EhrRecord", "EhrRecord")
                        .WithMany("Files")
                        .HasForeignKey("EhrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBH.EHR.Service.Models.Entities.EhrVersion", null)
                        .WithMany("Files")
                        .HasForeignKey("EhrVersionVersionId");

                    b.Navigation("EhrRecord");
                });

            modelBuilder.Entity("DBH.EHR.Service.Models.Entities.EhrSubscription", b =>
                {
                    b.HasOne("DBH.EHR.Service.Models.Entities.EhrRecord", "EhrRecord")
                        .WithMany()
                        .HasForeignKey("EhrId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EhrRecord");
                });

            modelBuilder.Entity("DBH.EHR.Service.Models.Entities.EhrVersion", b =>
                {
                    b.HasOne("DBH.EHR.Service.Models.Entities.EhrRecord", "EhrRecord")
                        .WithMany("Versions")
                        .HasForeignKey("EhrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBH.EHR.Service.Models.Entities.EhrVersion", "PreviousVersion")
                        .WithMany()
                        .HasForeignKey("PreviousVersionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EhrRecord");

                    b.Navigation("PreviousVersion");
                });

            modelBuilder.Entity("DBH.EHR.Service.Models.Entities.EhrRecord", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("DBH.EHR.Service.Models.Entities.EhrVersion", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
