version: "3.8"

services:
  auth-service:
    build:
      context: ../../
      dockerfile: src/DBH.Auth.Service/Dockerfile
    container_name: dbh_auth_service_test
    environment:
      - ConnectionStrings__PostgreSQL=Host=pg_primary;Port=5432;Database=dbh_identity;Username=admin;Password=dbh_123
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5101
    ports:
      - "5101:5101"
    networks:
      - dbh_network
    develop:
      watch:
        - action: rebuild
          path: ../../src/DBH.Auth.Service
        - action: rebuild
          path: ../../src/DBH.Auth.Service/DBH.Auth.Service.csproj
        - action: rebuild
          path: ../../src/DBH.Shared.Domain
        - action: rebuild
          path: ../../src/DBH.Shared.Contracts
        - action: rebuild
          path: ../../src/DBH.Shared.Infrastructure
    restart: always

networks:
  dbh_network:
    external: true
