// <auto-generated />
using System;
using DBH.Organization.Service.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DBH.Organization.Service.Migrations
{
    [DbContext(typeof(OrganizationDbContext))]
    [Migration("20260410132504_UpdateSeedingOrganization")]
    partial class UpdateSeedingOrganization
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DBH.Organization.Service.Models.Entities.Department", b =>
                {
                    b.Property<Guid>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DepartmentCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("department_code");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("department_name");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Floor")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("floor");

                    b.Property<Guid?>("HeadUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("head_user_id");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<Guid?>("ParentDepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_department_id");

                    b.Property<string>("PhoneExtension")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_extension");

                    b.Property<string>("RoomNumbers")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("room_numbers");

                    b.Property<int>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("DepartmentId");

                    b.HasIndex("OrgId");

                    b.HasIndex("ParentDepartmentId");

                    b.ToTable("departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222201"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "TM",
                            DepartmentName = "Khoa Tim mach",
                            Description = "Khoa Tim mach chuyen sau chan doan va dieu tri benh tim",
                            Floor = "3",
                            OrgId = new Guid("11111111-1111-1111-1111-111111111101"),
                            PhoneExtension = "3001",
                            RoomNumbers = "301-308",
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222204"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "DUOC",
                            DepartmentName = "Khoa Duoc",
                            Description = "Cap phat thuoc va tu van duoc lam sang",
                            Floor = "1",
                            OrgId = new Guid("11111111-1111-1111-1111-111111111101"),
                            PhoneExtension = "1002",
                            RoomNumbers = "101-104",
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222205"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "TN",
                            DepartmentName = "Quay tiep nhan",
                            Description = "Tiep nhan, dang ky va phan luong benh nhan",
                            Floor = "1",
                            OrgId = new Guid("11111111-1111-1111-1111-111111111101"),
                            PhoneExtension = "1001",
                            RoomNumbers = "L1-01",
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222203"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "NHI",
                            DepartmentName = "Khoa Nhi",
                            Description = "Khoa Nhi tong hop va cham soc tre em",
                            Floor = "2",
                            OrgId = new Guid("11111111-1111-1111-1111-111111111102"),
                            PhoneExtension = "2001",
                            RoomNumbers = "201-208",
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222202"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "CC",
                            DepartmentName = "Phong cap cuu",
                            Description = "Tiep nhan benh nhan cap cuu 24/7",
                            Floor = "1",
                            OrgId = new Guid("11111111-1111-1111-1111-111111111102"),
                            PhoneExtension = "1101",
                            RoomNumbers = "101-106",
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("DBH.Organization.Service.Models.Entities.Membership", b =>
                {
                    b.Property<Guid>("MembershipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("membership_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("EmployeeId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("employee_id");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("job_title");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("license_number");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("OrgPermissions")
                        .HasColumnType("jsonb")
                        .HasColumnName("org_permissions");

                    b.Property<string>("Qualifications")
                        .HasColumnType("jsonb")
                        .HasColumnName("qualifications");

                    b.Property<string>("Specialty")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("specialty");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("MembershipId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("OrgId");

                    b.ToTable("memberships");

                    b.HasData(
                        new
                        {
                            MembershipId = new Guid("33333333-3333-3333-3333-333333333301"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = "EMP-ADM-001",
                            JobTitle = "System Admin",
                            Notes = "Tai khoan quan tri he thong",
                            OrgId = new Guid("11111111-1111-1111-1111-111111111101"),
                            OrgPermissions = "[\"ALL\"]",
                            StartDate = new DateOnly(2024, 1, 1),
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            MembershipId = new Guid("33333333-3333-3333-3333-333333333302"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222201"),
                            EmployeeId = "EMP-DOC-001",
                            JobTitle = "Bac si chuyen khoa Tim mach",
                            LicenseNumber = "VN-DOC-001",
                            Notes = "Bac si chinh Khoa Tim mach",
                            OrgId = new Guid("11111111-1111-1111-1111-111111111101"),
                            OrgPermissions = "[\"VIEW_PATIENTS\",\"CREATE_RECORDS\"]",
                            Qualifications = "[\"Dai hoc Y Duoc TP.HCM\",\"Thac si Tim mach\"]",
                            Specialty = "Tim mach",
                            StartDate = new DateOnly(2024, 1, 10),
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            MembershipId = new Guid("33333333-3333-3333-3333-333333333303"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222204"),
                            EmployeeId = "EMP-STF-001",
                            JobTitle = "Duoc si lam sang",
                            LicenseNumber = "DS-001",
                            Notes = "Phu trach cap phat thuoc",
                            OrgId = new Guid("11111111-1111-1111-1111-111111111101"),
                            OrgPermissions = "[\"VIEW_PRESCRIPTIONS\",\"DISPENSE_DRUGS\"]",
                            Qualifications = "[\"Dai hoc Duoc\",\"Chung chi Duoc lam sang\"]",
                            Specialty = "Duoc lam sang",
                            StartDate = new DateOnly(2024, 1, 12),
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            MembershipId = new Guid("33333333-3333-3333-3333-333333333304"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222203"),
                            EmployeeId = "EMP-STF-002",
                            JobTitle = "Dieu duong Nhi khoa",
                            LicenseNumber = "DD-001",
                            Notes = "Dieu duong khoa Nhi",
                            OrgId = new Guid("11111111-1111-1111-1111-111111111102"),
                            OrgPermissions = "[\"VIEW_PATIENTS\",\"UPDATE_VITALS\"]",
                            Qualifications = "[\"Cu nhan Dieu duong\",\"Chung chi Nhi khoa\"]",
                            Specialty = "Dieu duong Nhi",
                            StartDate = new DateOnly(2024, 2, 1),
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd")
                        },
                        new
                        {
                            MembershipId = new Guid("33333333-3333-3333-3333-333333333305"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            JobTitle = "Patient",
                            Notes = "Benh nhan dang ky tai phong kham",
                            OrgId = new Guid("11111111-1111-1111-1111-111111111103"),
                            OrgPermissions = "[\"READ_OWN_RECORDS\"]",
                            StartDate = new DateOnly(2024, 1, 15),
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        },
                        new
                        {
                            MembershipId = new Guid("33333333-3333-3333-3333-333333333306"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222205"),
                            EmployeeId = "EMP-STF-003",
                            JobTitle = "Nhan vien tiep nhan",
                            LicenseNumber = "LT-001",
                            Notes = "Le tan khu tiep nhan",
                            OrgId = new Guid("11111111-1111-1111-1111-111111111101"),
                            OrgPermissions = "[\"VIEW_PATIENTS\",\"CREATE_APPOINTMENTS\"]",
                            Qualifications = "[\"Trung cap Y\",\"Chung chi tiep nhan benh nhan\"]",
                            Specialty = "Tiep nhan",
                            StartDate = new DateOnly(2024, 1, 20),
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff")
                        });
                });

            modelBuilder.Entity("DBH.Organization.Service.Models.Entities.Organization", b =>
                {
                    b.Property<Guid>("OrgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("Address")
                        .HasColumnType("jsonb")
                        .HasColumnName("address");

                    b.Property<string>("ContactInfo")
                        .HasColumnType("jsonb")
                        .HasColumnName("contact_info");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FabricCaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("fabric_ca_url");

                    b.Property<string>("FabricChannelPeers")
                        .HasColumnType("jsonb")
                        .HasColumnName("fabric_channel_peers");

                    b.Property<string>("FabricMspId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fabric_msp_id");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("license_number");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_url");

                    b.Property<string>("OrgCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("org_code");

                    b.Property<string>("OrgDid")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("org_did");

                    b.Property<string>("OrgName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("org_name");

                    b.Property<int>("OrgType")
                        .HasMaxLength(30)
                        .HasColumnType("integer")
                        .HasColumnName("org_type");

                    b.Property<string>("Settings")
                        .HasColumnType("jsonb")
                        .HasColumnName("settings");

                    b.Property<int>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TaxId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tax_id");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("timezone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.Property<Guid?>("VerifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("verified_by");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("website");

                    b.HasKey("OrgId");

                    b.ToTable("organizations");

                    b.HasData(
                        new
                        {
                            OrgId = new Guid("11111111-1111-1111-1111-111111111101"),
                            Address = "{\"line\":[\"215 Hong Bang\"],\"city\":\"Ho Chi Minh\",\"district\":\"Quan 5\",\"country\":\"VN\",\"postalCode\":\"700000\"}",
                            ContactInfo = "{\"phone\":\"028-3855-4269\",\"fax\":\"028-3855-4270\",\"email\":\"contact@bvdktu.vn\",\"hotline\":\"1900-1234\"}",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FabricCaUrl = "http://ca_hospital1:7054",
                            FabricChannelPeers = "[\"peer0.hospital1.ehr.com\"]",
                            FabricMspId = "Hospital1MSP",
                            LicenseNumber = "BV-HCM-001",
                            OrgCode = "BVDKTU",
                            OrgDid = "did:dbh:org:hospital-a",
                            OrgName = "Benh vien Da khoa Trung uong",
                            OrgType = 0,
                            Status = 0,
                            TaxId = "0301234567",
                            Timezone = "Asia/Ho_Chi_Minh",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            VerifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            VerifiedBy = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Website = "https://bvdktu.vn"
                        },
                        new
                        {
                            OrgId = new Guid("11111111-1111-1111-1111-111111111102"),
                            Address = "{\"line\":[\"341 Su Van Hanh\"],\"city\":\"Ho Chi Minh\",\"district\":\"Quan 10\",\"country\":\"VN\",\"postalCode\":\"700000\"}",
                            ContactInfo = "{\"phone\":\"028-3927-1119\",\"fax\":\"028-3927-1120\",\"email\":\"contact@bvnd1.vn\",\"hotline\":\"1900-5678\"}",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FabricCaUrl = "http://ca_hospital2:8054",
                            FabricChannelPeers = "[\"peer0.hospital2.ehr.com\"]",
                            FabricMspId = "Hospital2MSP",
                            LicenseNumber = "BV-HCM-002",
                            OrgCode = "BVND1",
                            OrgDid = "did:dbh:org:hospital-b",
                            OrgName = "Benh vien Nhi Dong 1",
                            OrgType = 0,
                            Status = 0,
                            TaxId = "0301234568",
                            Timezone = "Asia/Ho_Chi_Minh",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            VerifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            VerifiedBy = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Website = "https://bvnd1.vn"
                        },
                        new
                        {
                            OrgId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Address = "{\"line\":[\"123 Nguyen Hue\"],\"city\":\"Ho Chi Minh\",\"district\":\"Quan 1\",\"country\":\"VN\",\"postalCode\":\"700000\"}",
                            ContactInfo = "{\"phone\":\"028-3821-0000\",\"fax\":\"028-3821-0001\",\"email\":\"contact@pkdlsg.vn\",\"hotline\":\"1900-9012\"}",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FabricCaUrl = "http://ca_clinic:10054",
                            FabricChannelPeers = "[\"peer0.clinic.ehr.com\"]",
                            FabricMspId = "ClinicMSP",
                            LicenseNumber = "PK-HCM-001",
                            OrgCode = "PKDLSG",
                            OrgDid = "did:dbh:org:clinic-a",
                            OrgName = "Phong kham Da lieu Sai Gon",
                            OrgType = 1,
                            Status = 0,
                            TaxId = "0301234569",
                            Timezone = "Asia/Ho_Chi_Minh",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            VerifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            VerifiedBy = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Website = "https://pkdlsg.vn"
                        });
                });

            modelBuilder.Entity("DBH.Organization.Service.Models.Entities.PaymentConfig", b =>
                {
                    b.Property<Guid>("ConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("config_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EncryptedApiKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("encrypted_api_key");

                    b.Property<string>("EncryptedChecksumKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("encrypted_checksum_key");

                    b.Property<string>("EncryptedClientId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("encrypted_client_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ConfigId");

                    b.HasIndex("OrgId")
                        .IsUnique();

                    b.ToTable("payment_configs");
                });

            modelBuilder.Entity("DBH.Organization.Service.Models.Entities.Department", b =>
                {
                    b.HasOne("DBH.Organization.Service.Models.Entities.Organization", "Organization")
                        .WithMany("Departments")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBH.Organization.Service.Models.Entities.Department", "ParentDepartment")
                        .WithMany("ChildDepartments")
                        .HasForeignKey("ParentDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Organization");

                    b.Navigation("ParentDepartment");
                });

            modelBuilder.Entity("DBH.Organization.Service.Models.Entities.Membership", b =>
                {
                    b.HasOne("DBH.Organization.Service.Models.Entities.Department", "Department")
                        .WithMany("Memberships")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DBH.Organization.Service.Models.Entities.Organization", "Organization")
                        .WithMany("Memberships")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("DBH.Organization.Service.Models.Entities.PaymentConfig", b =>
                {
                    b.HasOne("DBH.Organization.Service.Models.Entities.Organization", "Organization")
                        .WithOne("PaymentConfig")
                        .HasForeignKey("DBH.Organization.Service.Models.Entities.PaymentConfig", "OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("DBH.Organization.Service.Models.Entities.Department", b =>
                {
                    b.Navigation("ChildDepartments");

                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("DBH.Organization.Service.Models.Entities.Organization", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Memberships");

                    b.Navigation("PaymentConfig");
                });
#pragma warning restore 612, 618
        }
    }
}
