// <auto-generated />
using System;
using DBH.Consent.Service.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DBH.Consent.Service.Migrations
{
    [DbContext(typeof(ConsentDbContext))]
    [Migration("20260415065522_RemoveConditionsColumn")]
    partial class RemoveConditionsColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DBH.Consent.Service.Models.Entities.AccessRequest", b =>
                {
                    b.Property<Guid>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<Guid?>("ConsentId")
                        .HasColumnType("uuid")
                        .HasColumnName("consent_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EhrId")
                        .HasColumnType("uuid")
                        .HasColumnName("ehr_id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PatientDid")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("patient_did");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<int>("Permission")
                        .HasMaxLength(20)
                        .HasColumnType("integer")
                        .HasColumnName("permission");

                    b.Property<int>("Purpose")
                        .HasMaxLength(30)
                        .HasColumnType("integer")
                        .HasColumnName("purpose");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<int>("RequestedDurationDays")
                        .HasColumnType("integer")
                        .HasColumnName("requested_duration_days");

                    b.Property<string>("RequesterDid")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("requester_did");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid")
                        .HasColumnName("requester_id");

                    b.Property<int>("RequesterType")
                        .HasMaxLength(30)
                        .HasColumnType("integer")
                        .HasColumnName("requester_type");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<string>("ResponseReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("response_reason");

                    b.Property<int>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("RequestId");

                    b.ToTable("access_requests");
                });

            modelBuilder.Entity("DBH.Consent.Service.Models.Entities.Consent", b =>
                {
                    b.Property<Guid>("ConsentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("consent_id");

                    b.Property<long?>("BlockchainBlockNum")
                        .HasColumnType("bigint")
                        .HasColumnName("blockchain_block_num");

                    b.Property<string>("BlockchainConsentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("blockchain_consent_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EhrId")
                        .HasColumnType("uuid")
                        .HasColumnName("ehr_id");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("GrantTxHash")
                        .HasMaxLength(66)
                        .HasColumnType("character varying(66)")
                        .HasColumnName("grant_tx_hash");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<string>("GranteeDid")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("grantee_did");

                    b.Property<Guid>("GranteeId")
                        .HasColumnType("uuid")
                        .HasColumnName("grantee_id");

                    b.Property<int>("GranteeType")
                        .HasMaxLength(30)
                        .HasColumnType("integer")
                        .HasColumnName("grantee_type");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("PatientDid")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("patient_did");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<int>("Permission")
                        .HasMaxLength(20)
                        .HasColumnType("integer")
                        .HasColumnName("permission");

                    b.Property<int>("Purpose")
                        .HasMaxLength(30)
                        .HasColumnType("integer")
                        .HasColumnName("purpose");

                    b.Property<string>("RevokeReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("revoke_reason");

                    b.Property<string>("RevokeTxHash")
                        .HasMaxLength(66)
                        .HasColumnType("character varying(66)")
                        .HasColumnName("revoke_tx_hash");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<int>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ConsentId");

                    b.ToTable("consents");
                });
#pragma warning restore 612, 618
        }
    }
}
